export const SIGN_UP = 'SAIGN_UP'
export const SIGN_UP_START = 'SAIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SAIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SAIGN_UP_FAIL'
export const CLEAR_SIGN_UP_DATA = 'CLEAR_SIGN_UP_DATA' 

export const SIGN_IN = 'SAIGN_IN'
export const SIGN_IN_START = 'SAIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SAIGN_IN_SUCCESS'
export const SIGN_IN_FAIL = 'SAIGN_IN_FAIL'
export const CLEAR_SIGN_IN_DATA = 'CLEAR_SIGN_IN_DATA' 

export const SIGN_OUT = 'SIGN_OUT'
export const LOG_OUT = 'LOG_OUT'
export const SIGN_OUT_COUNT_DOWN = 'SIGN_OUT_COUNT_DOWN'

export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS'


export const POSTS_INIT = 'POSTS_INIT'
export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const POSTS_COULD_NOT_BE_FETCHED = 'POSTS_COULD_NOT_BE_FETCHED'
export const POSTS_FETCHED_SUCCESSFULLY = 'POSTS_FETCHED_SUCCESSFULLY'

export const TAGS_INIT = 'TAGS_INIT'
export const FETCH_TAGS_START = 'FETCH_TAGS_START'
export const TAGS_FETCHED_SUCCESSFULLY = 'TAGS_FETCHED_SUCCESSFULLY'
export const TAGS_COULD_NOT_BE_FETCHED = 'TAGS_COULD_NOT_BE_FETCHED'

export const CREATE_POST_INIT = 'CREATE_POST_INIT'
export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const UPDATE_POST_INIT = 'UPDATE_POST_INIT'
export const UPDATE_POST_START = 'UPDATE_POST_START'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_INIT = 'DELETE_POST_INIT'
export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const CREATE_COMMENT_INIT = 'CREATE_COMMENT_INIT'
export const CREATE_COMMENT_START = 'CREATE_COMMENT_START'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'
