version: '3.7'

services:
  app:
    build:
      context: ./blog_back_end/
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./blog_back_end/:/blog_back_end/
    env_file: ./blog_back_end/.env
    environment:
      RAILS_ENV: development

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  redis:
   image: "redis:4.0-alpine"
   command: redis-server
   volumes:
      - "redis:/data"
  sidekiq:
    build:
      context: ./blog_back_end/
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - ./blog_back_end/:/blog_back_end/
    env_file: ./blog_back_end/.env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  frontend:
    build:
      context: ./blog_front_end/
    depends_on:
      - app
    volumes:
      - ./blog_front_end/:/blog_front_end/
      - ./blog_front_end/node_modules:/blog_front_end/node_modules
    command: npm start
    ports:
      - 3001:3001
volumes:
  db:
  redis: